#!/usr/bin/perl -w
#
# Copyright 2017, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

use strict;
use Text::Diff;

my $clangfmt = shift or die;
my $mode = shift or die;

sub check {
	my ($file) = @_;
	my $original;
	my $formatted;

	$formatted = `$clangfmt -style=file "$file"`;

	if ($mode eq 'check') {
		local $/=undef;
		open FILE, "$file" or die "Couldn't open file: $file";
		binmode FILE;
		$original = <FILE>;
		close FILE;

		my $diff = diff \$original, \$formatted;

		if ($diff ne "") {
			print "Style check using $clangfmt for file $file failed\n";
			print $diff;
			die "Style check using $clangfmt for file $file failed\n";
		}
	} elsif ($mode eq 'format') {
		local $/=undef;
		open FILE, '>', "$file" or die "Couldn't open file: $file";
		print FILE "$formatted";
		close FILE;
	} else {
		die 'unknown mode';
	}
}

foreach(@ARGV) {
	check($_)
}
