/*
SPDX-License-Identifier: BSD-3-Clause
Copyright 2019-2020, Intel Corporation

Jenkinsfile - pipeline with jobDSL scripts to create pmemkv and pmemkv_matrix jobs - to run with initial jenkins job.
*/

/* define common properties of pipelines: */

description_param = '''
	string {
		name('DESCRIPTION')
		defaultValue('')
		trim(true)
		description('description')
	}
'''

label_param = '''
	string {
		name('LABEL')
		defaultValue('fedora')
		trim(true)
		description("node to run job on: rhel8_1, openSUSE, fedora31, ubuntu19, debian10")
	}
'''

repo_url_param = '''
	string {
		name('REPO_URL')
		defaultValue('https://github.com/pmem/pmemkv.git')
		trim(true)
		description("Git repository address")
	}
'''

branch_param = '''
	string {
		name('BRANCH')
		defaultValue('master')
		trim(true)
		description("Repository's branch")
	}
'''

type_param = '''
	choiceParam('TEST_TYPE', ['normal', 'building', 'bindings', 'compatibility', 'coverity'], 'Type of tests')
'''

coverage_param = '''
	choiceParam('COVERAGE', ['yes', 'no'], 'Enable code coverage')
'''

gitlab_connection = '''
	properties {
		gitLabConnection {
			gitLabConnection('gitlabIT')
		}
	}
'''

email_options_param = '''
	string {
		name('EMAIL_RECIPIENTS')
		defaultValue('')
		trim(true)
		description("Recipients of the e-mail sent after execution, separated by the comma.")
	}
	booleanParam('SEND_RESULTS', true, 'Uncheck to disable sending email with report after execution')
'''

/* Loads pipeline scripts from repository */
def remote_definition(current_job_script_path) {
    return """
		definition {
			cpsScm {
				scm {
					git {
						remote {
							url('https://github.com/pmem/pmemkv.git')
							branch('${jenkins_files_branch_source}')
							scriptPath('${current_job_script_path}')
						}
					}
				}
			}
		}
	"""
}

/* this branch will be used to pull jobs when building Jenkinsfile job and for pulling repository when loading libraries in 'Prepare' stage: */
jenkins_files_branch_source = 'master'

environmental_variables = """
	environmentVariables {
		envs(
			api_lib: "jenkins_files/utils/jenkins/lib/api.groovy",
			lib_path: "jenkins_files/utils/jenkins/lib/",
			scripts_path: "jenkins_files/utils/jenkins/scripts/",
			jenkins_files_repo: "https://github.com/pmem/pmemkv.git",
			jenkins_files_branch: "*/${jenkins_files_branch_source}"
		)
	}
"""

triggers = '''
	triggers {
		gitlabPush {
			buildOnMergeRequestEvents(true)
			buildOnPushEvents(true)
			enableCiSkip(false)
			setBuildDescription(false)
			rebuildOpenMergeRequest('never')
		}
	}
'''

node {
	stage('pmemkv_linux'){
        jobDsl scriptText: """pipelineJob("pmemkv_linux") {
			parameters {
				${label_param}
				${branch_param}
				${type_param}
				${repo_url_param}
				${description_param}
				${coverage_param}
				${email_options_param}
			}
			${gitlab_connection}
			${environmental_variables}
			${triggers}
			${remote_definition 'utils/jenkins/pmemkv_linux.jenkins'}
		}"""
    }
    stage('pmemkv_linux_matrix'){
        jobDsl scriptText: """matrixJob("pmemkv_linux_matrix") {
        	parameters {
				matrixCombinationsParam('COMBINATIONS', '', 'choose which combinations to run')
				${branch_param}
				${coverage_param}
				${repo_url_param}
				${description_param}
				${email_options_param}
        	}
			axes {
		        text('DISTRO', 'ubuntu', 'ubuntuLTS', 'fedora')
		        text('TYPE', 'normal', 'building', 'bindings', 'compatibility', 'coverity')
		        label('master', 'master')
		    }
		    steps {
		        downstreamParameterized {
					trigger("pmemkv_linux") {
						parameters {
							predefinedProp('COV', '\${COVERAGE}')
							predefinedProp('TEST_TYPE', '\${TYPE}')
							predefinedProp('LABEL', '\${DISTRO}')
							predefinedProp('BRANCH', '\${BRANCH}')
							predefinedProp('REPO_URL', '\${REPO_URL}')
							predefinedProp('EMAIL_RECIPIENTS', '\${EMAIL_RECIPIENTS}')
							predefinedProp('SEND_EMAIL', '\${SEND_RESULTS}')
                            predefinedProp('DESCRIPTION', '\${DESCRIPTION}  #Triggered by pmemkv matrixJob #\${BUILD_NUMBER}   ->   \${JENKINS_URL}view/all/job/pmemkv_linux_matrix/\${BUILD_NUMBER}')
						}
					block {
						buildStepFailure('FAILURE')
						failure('FAILURE')
						unstable('UNSTABLE')
						}
					}
				}
		    }
		}"""
    }
}
